#!/bin/sh /etc/rc.common

# This is a service for 'xray-tproxy.sh' script. To use it do the following:
#   1. Setup xray-tproxy.sh (follow instructions from there)
#   2. Put this file into /etc/init.d/xray-tproxy
#   3. Make it executable: chmod +x /etc/init.d/xray-tproxy
#   4. Enable service: /etc/init.d/xray-tproxy enable
#   5. Start service:  /etc/init.d/xray-tproxy start
#   6. To check its status use: /etc/init.d/xray-tproxy status

START=99
STOP=15

EXTRA_COMMANDS="status"
EXTRA_HELP="        status          Check proxification status"

start() {
    /usr/bin/xray-tproxy.sh
}

stop() {
    /usr/bin/xray-tproxy.sh -s
}

status() {
    /usr/bin/xray-tproxy.sh -c
}
